server:
  port: 8080
spring:
  application:
    name: API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 940727

mybatis:
  configuration:
    map-underscore-to-camel-case: true